# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint Trajectory Interface to MoveIt
trajectory_controller:
  type: position_controllers/JointTrajectoryController

  joints:
    - robot1/joint1
    - robot1/joint2
    - robot1/joint3
    - robot1/joint4
    - robot1/joint5
    - robot1/joint6

  constraints:
    goal_time: 0.5
  state_publish_rate:  25
  action_monitor_rate: 30
  stop_trajectory_duration: 0.01
